repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      # Git Style
      - id: check-added-large-files # Prevent large files from commit (default=500kb)
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: forbid-new-submodules
      # TIP: Consider adding "no-commit-to-branch" hook to protect "main".

      # Common Errors
      - id: check-executables-have-shebangs
      - id: check-yaml # Validate yaml file syntax
      - id: end-of-file-fixer # Ensure files end in newline char
      - id: trailing-whitespace # Trim superfluous whitespace from eol
        args: [--markdown-linebreak-ext=md]

      # Security
      - id: detect-aws-credentials
        args: ["--allow-missing-credentials"]
      - id: detect-private-key

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.17
    hooks:
      - id: terraform-fmt
      - id: tflint

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.72.1
    hooks:
      - id: terraform_tfsec
      - id: tfupdate
        alias: tf-version-autoupdate
      - id: terraform_docs
        exclude: examples/*
        args:
          - --hook-config=--path-to-file=README.md
          - --hook-config=--add-to-existing-file=true
          - --hook-config=--create-file-if-not-exist=true
          - --args=--config=.terraform-docs.yaml
